apiVersion: v1
kind: Pod
metadata:
  name: app-volumeMounts
spec:
  containers:
  - name: demo
    image: gcr.io/k8s-test5/demo:v1.0.0
    volumeMounts:
    - name: app-volume
      mountPath: /app/data
  volumes:
  - name: app-volume
    emptyDir: {}
