apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secret-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-secret-env
  template:
    metadata:
      labels:
        app: app-secret-env
    spec:
      containers:
      - name: app-secret-env
        image: gcr.io/k8s-test5/demo:v1.0.0
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  secret-key: <insert base64 encoded secret key here>
