apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-job
spec:
  template:
    spec:
      containers:
      - name: cleanup-container
        image: cleanup-image
        command: ["sh", "-c", "cleanup-script.sh"]
      restartPolicy: Never
  backoffLimit: 4
